#:schema node_modules/wrangler/config-schema.json
name = "yumemi-frontend-engineer-codecheck"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
main = "./api/index.ts"

[assets]
not_found_handling = "single-page-application"
binding = "ASSETS"
